baseURL = "https://jisai.uk/"
title = "jisai"
theme = "lynx"

# lynx theme config
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
name = "jisai"
headline = "Composer/Arranger"
image = "img/profile.jpg"      # path relative to static directory

links = [
    { soundcloud = "https://soundcloud.com/jisai_w" },
    { x = "https://x.com/jisai_w" },
    { youtube = "https://youtube.com/@jisai_w" },
    { spotify = "https://open.spotify.com/artist/3Vtew6bb136AMeOn6H5SLb" },
    { bluesky = "https://bsky.app/profile/jisai-w.bsky.social" },
    { bandcamp = "https://jisai.bandcamp.com" },
    { discord = { href = "https://discord.gg/ttvRKepjCH", text = "Discord Server" } },
]

[module.hugoVersion]
extended = false
min = "0.86.1"
